services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
  app:
    build:
      context: .
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - "redis"

networks:
  default:
    driver: bridge
